### ISSUE TITLE
运行出现问题

### ISSUE THREAD

**Issue by ghost** [luern0313/CoupletWriter#1]
Traceback (most recent call last):
  File "D:\Apps\CoupletWriter-master\main.py", line 1, in <module>
    import jieba, random, json
ModuleNotFoundError: No module named 'jieba'

**Comment by luern0313** [comment]
先安装这个库

**Comment by ghost** [comment]
哦，知道了，谢谢！新年快乐

**Comment by luern0313** [comment]
秒回啊。。你也新年快乐
