### ISSUE TITLE
问题列表

### ISSUE THREAD

**Issue by ZGarry** [luern0313/CoupletWriter#2]
本人新手，如果不妥，多多体谅。
1/软件命名可做优化？
结构如下{A：{B:C}}，这样能否使结构更加清晰？
2/请问此处采取的具体给分算法名称是？每次加入一个新的词语就要重新遍历整个现有空间，并且需要更新同级别所有C。耗费时间极高。以我电脑为例，学习了约1.5h。
3/第二次运行时莫名报错，寻求帮助。
`JSONDecodeError: Expecting property name enclosed in double quotes: line 1 column 2 (char 1)`

**Comment by luern0313** [comment]
出的问题是py的字典和json一个用的是单引号一个是双引号，json解析才出错的，你可以手动把文件里单双引号替换下，也可以直接在release里下载学习好的

**Comment by luern0313** [comment]
至于算法问题。。刚开始做的时候没想到要做成现在这样。。结构什么的没设计好
